name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      app: ${{steps.filter.outputs.app}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Path filtering
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            core:
              - 'Dockerfile'
              - 'hn_core/**'

  build-and-push:
    needs: [changes]
    if: ${{ (github.ref_name == 'main') && (needs.changes.outputs.core == 'true') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure DO
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Login to DO registry
        run: |
          doctl registry login

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: |
            registry.digitalocean.com/hn-registry/hn-core:latest